import { HouseholdItem, PantryItem, Genre } from '@types';

export const PANTRY_INVENTORY: PantryItem[] = [
  { name: 'juice', unit: 'cup' },
  { name: 'olive oil', unit: 'tbsp' },
  { name: 'vegetable oil', unit: 'tbsp' },
  { name: 'shortening', unit: 'tbsp' },
  { name: 'flour', unit: 'cup' },
  { name: 'sugar', unit: 'cup' },
  { name: 'eggs', unit: 'unit' },
  { name: 'rice', unit: 'cup' },
  { name: 'butter', unit: 'cup' },
  { name: 'sour cream', unit: 'cup' },
  { name: 'milk', unit: 'cup' },
  { name: 'heavy whipping cream', unit: 'cup' },
  { name: 'yogurt', unit: 'cup' },
  { name: 'soy sauce', unit: 'tbsp' },
  { name: 'fish sauce', unit: 'tbsp' },
  { name: 'teriyaki sauce', unit: 'tbsp' },
  { name: 'worcestershire sauce', unit: 'tbsp' },
  { name: 'balsamic vinegar', unit: 'tbsp' },
  { name: 'apple cider vinegar', unit: 'tbsp' },
  { name: 'white vinegar', unit: 'tbsp' },
  { name: 'garlic', unit: 'clove' },
  { name: 'onion', unit: 'unit' },
  { name: 'carrots', unit: 'unit' },
  { name: 'celery', unit: 'unit' },
  { name: 'potatoes', unit: 'unit' },
  { name: 'thai chilies', unit: 'unit' },
  { name: 'dried red chilies', unit: 'unit' },
  { name: 'sweet chili sauce', unit: 'tbsp' },
  { name: 'cajun seasoning', unit: 'tbsp' },
  { name: 'curry leaves (bay leaves)', unit: 'unit' },
  { name: 'peas', unit: 'cup' },
  { name: 'tomato sauce', unit: 'cup' },
  { name: 'diced tomatoes', unit: 'cup' },
  { name: 'chicken stock', unit: 'cup' },
  { name: 'beef stock', unit: 'cup' },
  { name: 'thyme', unit: 'tbsp' },
  { name: 'oregano', unit: 'tbsp' },
  { name: 'coriander', unit: 'tbsp' },
  { name: 'cumin', unit: 'tbsp' },
  { name: 'cinnamon', unit: 'tbsp' },
  { name: 'nutmeg', unit: 'tbsp' },
  { name: 'cloves', unit: 'tbsp' },
  { name: 'allspice', unit: 'tbsp' },
  { name: 'ginger', unit: 'tbsp' },
  { name: 'sage', unit: 'tbsp' },
  { name: 'seasoned salt', unit: 'tbsp' },
  { name: 'chili powder', unit: 'tbsp' },
  { name: 'cayenne pepper', unit: 'tbsp' },
  { name: 'paprika', unit: 'tbsp' },
  { name: 'basil', unit: 'tbsp' },
  { name: 'poppy seeds', unit: 'tbsp' },
  { name: 'sesame seeds', unit: 'tbsp' },
  { name: 'curry leaves (bay leaves)', unit: 'unit' },
  { name: 'tuna', unit: 'oz' },
  { name: 'nuts', unit: 'cup'},
  { name: 'mustard seeds', unit: 'tbsp' },
  { name: 'anise or fennel seeds', unit: 'tbsp' },
  { name: 'cardamom pod', unit: 'unit' },
  { name: 'sadaf fatoush seasoning', unit: 'tbsp' },
  { name: 'pomegranate molasses', unit: 'tbsp' },
  { name: 'cardamom', unit: 'unit' },
  { name: 'rosemary', unit: 'tbsp' },
  { name: 'saffron', unit: 'tbsp' },
  { name: 'jam', unit: 'cup'},
  { name: 'peanut-butter', unit: 'cup'},
  { name: 'bread', unit: 'unit'},
  { name: 'crackers', unit: 'unit'},
  { name: 'hamburger buns', unit: 'unit'},
  { name: 'spicy pickles', unit: 'unit'},
  { name: 'ketchup', unit: 'cup'},
  { name: 'mayonnaise', unit: 'cup'},
  { name: 'mustard', unit: 'cup'},
  { name: 'poupon mustard', unit: 'cup'},
  { name: 'tapatio', unit: 'tsp'},
  { name: 'peperoncino peppers', unit: 'unit'},
  { name: 'celery salt', unit: 'tsp'},
  { name: 'refried beans', unit: 'cup'},
  { name: 'quick oats', unit: 'cup'},
  { name: 'siracha', unit: 'tsp'},
  { name: 'honey', unit: 'cup'},
  { name: 'ice', unit: 'cup'},
  { name: 'tea', unit: 'cup'},
  { name: 'coffee', unit: 'cup'},
  { name: 'espresso powder', unit: 'cup'},
  { name: 'cocoa powder', unit: 'cup'},
  { name: 'cornmeal', unit: 'cup'},
  { name: 'flour', unit: 'cup'},
  { name: 'almond flour', unit: 'cup'},
  { name: 'brown sugar', unit: 'cup'},
  { name: 'powdered sugar', unit: 'cup'},
  { name: 'chocolate chips', unit: 'cup'},
  { name: 'cheddar cheese', unit: 'cup' },
  { name: 'baking powder', unit: 'tsp'},
  { name: 'baking soda', unit: 'tsp'},
  { name: 'yeast', unit: 'tsp'},
  { name: 'vanilla extract', unit: 'tsp'},
  { name: 'almond extract', unit: 'tsp'},
  { name: '505 green chili sauce', unit: 'oz'},
  { name: '505 green chili', unit: 'oz'},
  { name: 'yeast rolls', unit: 'unit'},
  { name: 'hashbrowns', unit: 'cup'},
  { name: 'guerrero rousimas tortillas', unit: 'unit'},
  { name: 'muffin/cupcake liners', unit: 'unit'}
];

export const HOUSEHOLD_INVENTORY: HouseholdItem[] = [
  { id: 'paper-towels', name: 'paper towels', category: 'household' },
  { id: 'toilet-paper', name: 'toilet paper', category: 'household' },
  { id: 'dish-soap', name: 'dish soap', category: 'household' },
  { id: 'dish-detergent', name: 'dish detergent', category: 'household' },
  { id: 'sponges', name: 'sponges', category: 'household' },
  { id: 'laundry-detergent', name: 'laundry detergent', category: 'household' },
  { id: 'glass-cleaner', name: 'glass cleaner', category: 'household' },
  { id: 'furniture-polish', name: 'furniture polish', category: 'household' },
  { id: 'air-freshener', name: 'air freshener', category: 'household' },
  { id: 'bleach', name: 'bleach', category: 'household' },
  { id: 'vinegar', name: 'vinegar', category: 'pantry' },
  { id: 'cleaning-wipes', name: 'cleaning wipes', category: 'household' },
  { id: 'steel-cleaner', name: 'steel cleaner', category: 'household' },
  { id: 'stain-remover', name: 'stain remover', category: 'household' },
  { id: 'toilet-cleaner', name: 'toilet cleaner', category: 'household' },
  { id: 'pine-sol', name: 'pine sol', category: 'household' },
  { id: 'shampoo', name: 'shampoo', category: 'hygiene' },
  { id: 'conditioner', name: 'conditioner', category: 'hygiene' },
  { id: 'allergy-med', name: 'allergy med', category: 'hygiene' },
  { id: 'toothpaste', name: 'toothpaste', category: 'hygiene' },
  { id: 'toothbrushes', name: 'toothbrushes', category: 'hygiene' },
  { id: 'body-wash', name: 'body wash', category: 'hygiene' },
  { id: 'hand-soap', name: 'hand soap', category: 'hygiene' },
  { id: 'razors', name: 'razors', category: 'hygiene' },
  { id: 'deodorant', name: 'deodorant', category: 'hygiene' },
  { id: 'floss', name: 'floss', category: 'hygiene' },
  { id: 'mouthwash', name: 'mouthwash', category: 'hygiene' },
  { id: 'contact-solution', name: 'contact solution', category: 'hygiene' },
  { id: 'rubbing-alcohol', name: 'rubbing alcohol', category: 'hygiene' },
  { id: 'band-aids', name: 'band-aids', category: 'hygiene' },
  { id: 'tampons', name: 'tampons', category: 'hygiene' },
  { id: 'liners', name: 'liners', category: 'hygiene' },
  { id: 'q-tips', name: 'q-tips', category: 'hygiene' },
  { id: 'lotion', name: 'lotion', category: 'hygiene' },
  { id: 'hair-treatment', name: 'hair treatment', category: 'hygiene' },
  { id: 'chapstick', name: 'chapstick', category: 'hygiene' },
  { id: 'tissues', name: 'tissues', category: 'hygiene' },
  { id: 'cotton-pads', name: 'cotton pads', category: 'hygiene' },
  { id: 'superglue', name: 'superglue', category: 'household' },
  { id: 'paper-plates', name: 'paper plates', category: 'household' },
  { id: 'paper-cups', name: 'paper cups', category: 'household' },
  { id: 'plastic-utensils', name: 'plastic utensils', category: 'household' },
  { id: 'ziplock-bags', name: 'ziplock bags', category: 'household' },
  { id: 'trash-bags', name: 'trash bags', category: 'household' },
  { id: 'plastic-wrap', name: 'plastic wrap', category: 'household' },
  { id: 'tin-foil', name: 'tin foil', category: 'household' },
  { id: 'wax-paper', name: 'wax paper', category: 'household' },
  { id: 'parchment-sheets', name: 'parchment sheets', category: 'household' },
  { id: 'food-storage-containers', name: 'food storage containers', category: 'household' },
  { id: 'cat-food', name: 'cat food', category: 'pet' },
  { id: 'cat-treats', name: 'cat treats', category: 'pet' },
  { id: 'outdoor-trash-bags', name: 'outdoor trash bags', category: 'pet' },
  { id: 'lint-roller', name: 'lint roller', category: 'pet' },
  { id: 'goat-milk', name: 'goat milk', category: 'baby' },
  { id: 'baby-snacks', name: 'baby snacks', category: 'baby' },
  { id: 'applesauce', name: 'applesauce', category: 'baby' },
  { id: 'diapers', name: 'diapers', category: 'baby' },
  { id: 'baby-wipes', name: 'baby wipes', category: 'baby' },
  { id: 'rash-cream', name: 'rash cream', category: 'baby' },
  // food items
  { id: 'juice', name: 'juice', category: 'beverages' },
  { id: 'milk', name: 'milk', category: 'dairy' },
  { id: 'kombucha', name: 'kombucha', category: 'beverages' },
  { id: 'alcohol', name: 'alcohol', category: 'beverages' },
  { id: 'tuna', name: 'tuna', category: 'pantry'},
  { id: 'bread', name: 'bread', category: 'snacks'},
  { id: 'spicy-pickles', name: 'spicy pickles', category: 'pantry'},
  { id: 'ketchup', name: 'ketchup', category: 'pantry'},
  { id: 'mayonnaise', name: 'mayonnaise', category: 'pantry'},
  { id: 'mustard', name: 'mustard', category: 'pantry'},
  { id: 'tapatio', name: 'tapatio', category: 'pantry'},
  { id: 'ice', name: 'ice', category: 'beverages'},
  { id: 'tea', name: 'tea', category: 'beverages'},
  { id: 'espresso-powder', name: 'espresso powder', category: 'beverages'},
  { id: 'sugar', name: 'sugar', category: 'baking'},
  { id: 'brown-sugar', name: 'brown sugar', category: 'baking'},
  { id: 'fresh-fruit', name: 'fresh fruit', category: 'snacks'},
  { id: 'eggs', name: 'eggs', category: 'dairy'},
  { id: 'yogurt', name: 'yogurt', category: 'dairy'},
  { id: 'heavy-whipping-cream', name: 'heavy whipping cream', category: 'dairy'},
  { id: 'butter', name: 'butter', category: 'dairy'},
  { id: 'olive-oil', name: 'olive oil', category: 'pantry'},
  { id: 'breakfast-sausage', name: 'breakfast sausage', category: 'butchery'},
  { id: 'breakfast-potatoes', name: 'breakfast potatoes', category: 'frozen'},
  { id: 'pancake-mix', name: 'pancake mix', category: 'pantry'},
  { id: 'cheddar-cheese', name: 'cheddar cheese', category: 'dairy'},
  { id: 'thyme', name: 'thyme', category: 'spices'},
  { id: 'salt', name: 'salt', category: 'spices'},
  { id: 'black-pepper', name: 'black pepper', category: 'spices'},
  { id: 'seasoned-salt', name: 'seasoned salt', category: 'spices'}
];


