import { Meal } from '@types';

export const MEALS: Meal[] = [

  {
    id: 'green-enchiladas',
    name: 'Green Enchiladas',
    description: 'Green tomatillo enchiladas with white cheese and sour cream',
    ingredients: [
      { name: 'green tomatillos', unit: 'unit', amount: 10, genre: 'produce' },
      { name: 'monterey jack cheese', unit: 'cup', amount: 2, genre: 'dairy' },
      { name: 'guerrero rouisimas tortillas', unit: 'unit', amount: 10, genre: 'bakery' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'poblano peppers', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'jalapeno peppers', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'anaheim chilies', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'rotisserie chicken', unit: 'unit', amount: 1, genre: 'butchery' },
      { name: 'cream cheese', unit: 'tbsp', amount: 8, genre: 'dairy' },
      { name: 'cilantro', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'sour cream', unit: 'cup', amount: 1, genre: 'dairy' },
    ],
    timeMinutes: 60,
    multitaskable: true,
    cuisine: 'Mexican',
    meatType: 'chicken',
    priceLevel: '$',
    difficulty: 'medium',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: ['spanish-rice','elote'],
    recommendedSideExtraIngredients: [
      { name: 'refried beans', unit: 'oz', amount: 7, genre: 'pantry' }
    ]
  },
  {
    id: 'red-enchiladas',
    name: 'Red Enchiladas',
    description: 'Red chili enchiladas with yellow cheese and sour cream',
    ingredients: [
      { name: 'rotisserie chicken', unit: 'unit', amount: 1, genre: 'butchery' },
      { name: 'guerrero rousimas tortillas', unit: 'unit', amount: 10, genre: 'bakery' },
      { name: 'colby jack cheese', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'chili powder', unit: 'tbsp', amount: 4, genre: 'spices' },
      { name: 'cumin', unit: 'tbsp', amount: 0., genre: 'spices' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'olive oil', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'el pato tomato sauce', unit: 'oz', amount: 3, genre: 'produce' },
      { name: 'oregano', unit: 'tsp', amount: 0.5, genre: 'spices' },
      { name: 'flour', unit: 'tbsp', amount: 2, genre: 'baking' },
      { name: 'chicken stock', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: 'sour cream', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'cilantro', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'lime', unit: 'unit', amount: 2, genre: 'produce' }
    ],
    timeMinutes: 60,
    multitaskable: true,
    cuisine: 'Mexican',
    meatType: 'chicken',
    priceLevel: '$',
    difficulty: 'medium',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: ['spanish-rice','elote','guacamole-snack'],
    recommendedSideExtraIngredients: [
      { name: 'refried beans', unit: 'oz', amount: 7, genre: 'pantry' }
    ]
  },
  {
    id: 'white-enchiladas',
    name: 'White Enchiladas',
    description: 'White chicken enchiladas with sour cream and green chili',
    ingredients: [
      { name: 'rotisserie chicken', unit: 'unit', amount: 1, genre: 'butchery' },
      { name: 'cream cheese', unit: 'tbsp', amount: 8, genre: 'dairy' },
      { name: 'guerrero rousimas tortillas', unit: 'unit', amount: 10, genre: 'bakery' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'sour cream', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'butter', unit: 'tbsp', amount: 4, genre: 'dairy' },
      { name: 'flour', unit: 'tbsp', amount: 2, genre: 'baking' },
      { name: 'chicken stock', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: '505 green chili sauce', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'cilantro', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'lime', unit: 'unit', amount: 2, genre: 'produce' }
    ],
    timeMinutes: 60,
    multitaskable: true,
    cuisine: 'Mexican',
    meatType: 'chicken',
    priceLevel: '$',
    difficulty: 'medium',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: ['spanish-rice','elote','guacamole-snack'],
    recommendedSideExtraIngredients: [
      { name: 'refried beans', unit: 'oz', amount: 7, genre: 'pantry' }
    ]
  },
  { id: 'fajitas',
    name: 'Chicken Fajitas',
    description: 'Chicken fajitas with mushrooms, vegetables, cheese and sour cream',
    ingredients: [
      { name: 'chicken breast', unit: 'lb', amount: 3, genre: 'butchery' },
      { name: 'mushrooms', unit: 'cup', amount: 1, genre: 'produce' },
      { name: 'bell peppers', unit: 'unit', amount: 3, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'sour cream', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'colby jack cheese', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'guerrero rousimas tortillas', unit: 'unit', amount: 10, genre: 'bakery' },
      { name: 'cilantro', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'lime', unit: 'unit', amount: 2, genre: 'produce' },
      { name: 'cumin', unit: 'tbsp', amount: 0.5, genre: 'spices' },
      { name: 'chili powder', unit: 'tbsp', amount: 0.5, genre: 'spices' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'olive oil', unit: 'tbsp', amount: 2, genre: 'pantry' }
    ],
    timeMinutes: 40,
    multitaskable: true,
    cuisine: 'Mexican',
    meatType: 'chicken',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: ['spanish-rice','elote'],
    recommendedSideExtraIngredients: [
      { name: 'refried beans', unit: 'oz', amount: 7, genre: 'pantry' }
    ]
  },
  { id: 'machaca-tacos',
    name: 'Machaca Tacos',
    description: 'Mexican machaca (chipotle shredded beef roast) tacos',
    ingredients: [
      { name: 'beef chuck roast', unit: 'lb', amount: 6, genre: 'butchery' },
      { name: 'chipotle peppers', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'guerrero rouisimas tortillas', unit: 'unit', amount: 10, genre: 'bakery' },
      { name: 'cilantro', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'lime', unit: 'unit', amount: 2, genre: 'produce' },
      { name: 'sour cream', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'queso fresco', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'onion (red)', unit: 'unit', amount: 0.25, genre: 'produce' },
      { name: 'cabbage', unit: 'unit', amount: 0.25, genre: 'produce' },
      { name: 'cucumber', unit: 'unit', amount: 0.25, genre: 'produce' }
    ],
    timeMinutes: 300,
    multitaskable: true,
    cuisine: 'Mexican',
    meatType: 'beef',
    priceLevel: '$$$',
    difficulty: 'medium',
    timeIntensity: 'long',
    dishType: 'main',
    recommendedSideMealIds: ['spanish-rice','elote'],
    recommendedSideExtraIngredients: [
      { name: 'refried beans', unit: 'oz', amount: 7, genre: 'pantry' }
    ]
  },
  { id: 'ranch-tacos',
    name: 'Ranch Chicken Tacos',
    description: 'Crispy ranch fried chicken tacos with lettuce, cheese, and guacamole',
    ingredients: [
      { name: 'chicken tenderloins', unit: 'lb', amount: 3, genre: 'butchery' },
      { name: 'ranch dip mix packet', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'sour cream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'buttermilk', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'eggs', unit: 'unit', amount: 2, genre: 'dairy' },
      { name: 'ranch tortilla chips', unit: 'cup', amount: 1.5, genre: 'snacks' },
      { name: 'vegetable oil', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: 'avocado', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'queso fresco', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'lettuce', unit: 'unit', amount: 0.25, genre: 'produce' },
      { name: 'tomato', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'jalapeno peppers', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'onion (red)', unit: 'unit', amount: 0.25, genre: 'produce' },
      { name: 'guerrero rouisimas tortillas', unit: 'unit', amount: 10, genre: 'bakery' },
      { name: 'pomegranate seeds', unit: 'cup', amount: 0.25, genre: 'produce' },
      { name: 'lime', unit: 'unit', amount: 2, genre: 'produce' }
    ],
    timeMinutes: 50,
    multitaskable: false,
    cuisine: 'Mexican',
    meatType: 'chicken',
    priceLevel: '$$',
    difficulty: 'medium',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: ['spanish-rice','elote'],
    recommendedSideExtraIngredients: [
      { name: 'refried beans', unit: 'oz', amount: 7, genre: 'pantry' }
    ]
  },
  { id: 'spanish-rice',
    name: 'Spanish Rice',
    description: 'Spanish rice with tomatoes, onions, and garlic',
    ingredients: [
      { name: 'rice', unit: 'cup', amount: 2, genre: 'pantry' },
      { name: 'el pato tomato sauce', unit: 'oz', amount: 3, genre: 'produce' },
      { name: 'beef stock', unit: 'cup', amount: 0.5, genre: 'pantry' }
    ],
    timeMinutes: 30,
    multitaskable: true,
    cuisine: 'Mexican',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side'
  },
  { id: 'elote',
    name: 'Elote',
    description: 'Mexican street corn with mayonnaise, cotija cheese, and lime',
    ingredients: [
      { name: 'corn', unit: 'unit', amount: 4, genre: 'produce' },
      { name: 'tajin mayo', unit: 'cup', amount: 0.25, genre: 'pantry' },
      { name: 'queso fresco', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'lime', unit: 'unit', amount: 2, genre: 'produce' },
      { name: 'cilantro', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'jalapeno peppers', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'onion (red or white)', unit: 'unit', amount: 0.25, genre: 'produce' }
    ],
    timeMinutes: 30,
    multitaskable: false,
    cuisine: 'Mexican',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side'
  },
  {
    id: 'spaghetti-bolognese',
    name: 'Spaghetti Bolognese',
    description: 'Classic Italian pasta with rich meat sauce',
    ingredients: [
      { name: 'spaghetti', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'ground beef', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'mushrooms', unit: 'cup', amount: 1, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'tomato sauce', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'tomato paste', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'diced tomatoes', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'oregano', unit: 'tsp', amount: 0.5, genre: 'spices' },
      { name: 'basil', unit: 'tsp', amount: 0.5, genre: 'spices' },
      { name: 'thyme', unit: 'tsp', amount: 0.5, genre: 'spices' }
    ],
    timeMinutes: 30,
    multitaskable: false,
    cuisine: 'Italian',
    meatType: 'beef',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: ['caesar-salad'],
    recommendedSideExtraIngredients: [
      { name: 'garlic bread (frozen)', unit: 'unit', amount: 1, genre: 'frozen' },
      { name: 'french bread', unit: 'unit', amount: 0.5, genre: 'bakery' },
      { name: 'bread sticks', unit: 'unit', amount: 1, genre: 'frozen' },
      { name: 'yeast rolls', unit: 'unit', amount: 0.25, genre: 'frozen' }
    ]
  },
  {
    id: 'beef-stroganoff',
    name: 'Beef Stroganoff',
    description: 'Classic Russian beef stroganoff with mushrooms and onions',
    ingredients: [
      { name: 'beef tenderloin', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'mushrooms', unit: 'cup', amount: 1, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'beef stock', unit: 'cup', amount: 0.5, genre: 'pantry' },
      { name: 'extra wide egg noodles', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'sour cream', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'butter', unit: 'tbsp', amount: 4, genre: 'dairy' }
    ],
    timeMinutes: 40,
    multitaskable: false,
    cuisine: 'Slavic',
    meatType: 'beef',
    priceLevel: '$$$',
    difficulty: 'medium',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: ['seasonal-berry-salad'],
    recommendedSideExtraIngredients: [
      { name: 'yeast rolls', unit: 'unit', amount: 0.25, genre: 'frozen' },
      { name: 'french bread', unit: 'unit', amount: 0.5, genre: 'bakery' }
    ]
  },
  {
    id: 'chipotle-pasta',
    name: 'Chipotle Pasta',
    description: 'Creamy pasta with spicy chipotle sauce. You may substitute the chicken for meatballs and/or sliced Italian sausage.',
    ingredients: [
      { name: 'rigatoni pasta', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'rotisserie chicken', unit: 'lb', amount: 0.5, genre: 'butchery' },
      { name: 'pickled red peppers', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'chipotle peppers', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.25, genre: 'produce' },
      { name: 'diced tomatoes', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'tomato sauce', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'heavy whipping cream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'gouda cheese', unit: 'unit', amount: 1, genre: 'deli' },
      { name: 'oregano', unit: 'tsp', amount: 0.5, genre: 'spices' }
    ],
    timeMinutes: 30,
    multitaskable: false,
    cuisine: 'Italian',
    meatType: 'chicken',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: ['caesar-salad'],
    recommendedSideExtraIngredients: [
      { name: 'garlic bread (frozen)', unit: 'unit', amount: 1, genre: 'frozen' },
      { name: 'french bread', unit: 'unit', amount: 0.5, genre: 'bakery' },
      { name: 'bread sticks', unit: 'unit', amount: 1, genre: 'frozen' },
      { name: 'yeast rolls', unit: 'unit', amount: 0.25, genre: 'frozen' }
    ]
  },
  {
    id: 'lasagna',
    name: 'Lasagna',
    description: 'Classic Italian lasagna with layers of pasta, meat, and cheese',
    ingredients: [
      { name: 'lasagna noodles', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'hot italian sausage', unit: 'lb', amount: 2, genre: 'pantry' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'diced tomatoes', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'tomato paste', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'ricotta cheese', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'parmesan cheese', unit: 'cup', amount: 1, genre: 'deli' },
      { name: 'mozzarella cheese', unit: 'cup', amount: 2, genre: 'dairy' },
      { name: 'eggs', unit: 'unit', amount: 1, genre: 'dairy' },
      { name: 'basil', unit: 'tbsp', amount: 1, genre: 'spices' },
      { name: 'oregano', unit: 'tbsp', amount: 1, genre: 'spices' }
    ],
    timeMinutes: 50,
    multitaskable: false,
    cuisine: 'Italian',
    meatType: 'pork',
    priceLevel: '$$',
    difficulty: 'medium',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: ['caesar-salad'],
    recommendedSideExtraIngredients: [
      { name: 'garlic bread (frozen)', unit: 'unit', amount: 1, genre: 'frozen' },
      { name: 'french bread', unit: 'unit', amount: 0.5, genre: 'bakery' },
      { name: 'bread sticks', unit: 'unit', amount: 1, genre: 'frozen' }
    ]
  },
  {
    id: 'fettuccine-alfredo',
    name: 'Fettuccine Alfredo',
    description: 'Creamy fettuccine with Alfredo sauce and chicken',
    ingredients: [
      { name: 'fettuccine pasta', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'rotisserie chicken', unit: 'unit', amount: 0.5, genre: 'butchery' },
      { name: 'heavy whipping cream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'butter', unit: 'tbsp', amount: 8, genre: 'dairy' },
      { name: 'flour', unit: 'cup', amount: 0.25, genre: 'baking' },
      { name: 'parmesan cheese', unit: 'cup', amount: 2, genre: 'deli' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'nutmeg', unit: 'tsp', amount: 0.5, genre: 'spices' }
    ],
    timeMinutes: 30,
    multitaskable: false,
    cuisine: 'Italian',
    meatType: 'chicken',
    priceLevel: '$$',
    difficulty: 'medium',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: ['caesar-salad'],
    recommendedSideExtraIngredients: [
      { name: 'garlic bread (frozen)', unit: 'unit', amount: 1, genre: 'frozen' },
      { name: 'french bread', unit: 'unit', amount: 0.5, genre: 'bakery' },
      { name: 'bread sticks', unit: 'unit', amount: 1, genre: 'frozen' }
    ]
  },
  {
    id: 'mac-and-cheese',
    name: 'Green Chili Mac and Cheese',
    description: 'Creamy mac and cheese with spicy green chili',
    ingredients: [
      { name: 'macaroni', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: '505 green chili', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'heavy whipping cream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'butter', unit: 'tbsp', amount: 4, genre: 'dairy' },
      { name: 'flour', unit: 'cup', amount: 0.125, genre: 'baking' },
      { name: 'milk', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'cheddar cheese', unit: 'cup', amount: 2, genre: 'dairy' },
      { name: 'monterey jack cheese', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'gouda cheese', unit: 'unit', amount: 1, genre: 'deli' }
    ],
    timeMinutes: 30,
    multitaskable: false,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$$',
    difficulty: 'medium',
    timeIntensity: 'quick',
    dishType: 'side',
    extraType: 'snack'
  },
  {
    id: 'deviled-eggs',
    name: 'Deviled Eggs',
    description: 'Deviled eggs with mayo, mustard, and spices',
    ingredients: [
      { name: 'eggs', unit: 'unit', amount: 6, genre: 'dairy' },
      { name: 'mayo', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'poupon mustard', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'apple cider vinegar', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'paprika', unit: 'tsp', amount: 0.5, genre: 'spices' }
    ],
    timeMinutes: 20,
    multitaskable: false,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side',
    extraType: 'snack'
  },
  {
    id: 'chicken-cordon-bleu-pasta',
    name: 'Chicken Cordon Bleu Pasta',
    description: 'Creamy pasta with chicken, bacon, and cheese',
    ingredients: [
      { name: 'rotisserie chicken', unit: 'unit', amount: 0.5, genre: 'butchery' },
      { name: 'bacon', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'monterey jack cheese', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'bowtie pasta', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'panko shrimp', unit: 'cup', amount: 1, genre: 'frozen' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.25, genre: 'produce' },
      { name: 'heavy whipping cream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'butter', unit: 'tbsp', amount: 4, genre: 'dairy' },
      { name: 'flour', unit: 'cup', amount: 0.125, genre: 'baking' }
    ],
    timeMinutes: 50,
    multitaskable: false,
    cuisine: 'American',
    meatType: 'chicken',
    priceLevel: '$$',
    difficulty: 'medium',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: ['seasonal-berry-salad'],
    recommendedSideExtraIngredients: [
      { name: 'garlic bread (frozen)', unit: 'unit', amount: 1, genre: 'frozen' }
    ]
  },
  {
    id: 'meatloaf',
    name: 'Meatloaf',
    description: 'Classic American meatloaf with cracker crumbs, tomatoes, and parmesan',
    ingredients: [
      { name: 'ground beef', unit: 'lb', amount: 3, genre: 'butchery' },
      { name: 'crackers', unit: 'cup', amount: 1, genre: 'snacks' },
      { name: 'quick oats', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'eggs', unit: 'unit', amount: 1, genre: 'dairy' },
      { name: 'grated parmesan', unit: 'cup', amount: 1, genre: 'deli' },
      { name: 'worcestershire sauce', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'diced tomatoes', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'seasoned salt', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'ketchup', unit: 'cup', amount: 0.25, genre: 'pantry' },
      { name: 'poupon mustard', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'brown sugar', unit: 'cup', amount: 0.25, genre: 'baking' },
    ],
    timeMinutes: 60,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'beef',
    priceLevel: '$$',
    difficulty: 'easy',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: ['mashed-potatoes','seasonal-berry-salad'],
    recommendedSideExtraIngredients: [
      { name: 'canned green beans', unit: 'oz', amount: 14, genre: 'pantry' },
      { name: 'stuffing mix', unit: 'unit', amount: 1, genre: 'pantry' }
    ]
  },
  {
    id: 'pot-roast',
    name: 'Pot Roast',
    description: 'Pot roast with potatoes, carrots, and onions',
    ingredients: [
      { name: 'beef roast', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'potatoes', unit: 'unit', amount: 4, genre: 'produce' },
      { name: 'carrots', unit: 'unit', amount: 2, genre: 'produce' },
      { name: 'onions', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'beef stock', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'thyme', unit: 'tbsp', amount: 1, genre: 'spices' },
      { name: 'bay leaves', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'gravy mix', unit: 'unit', amount: 1, genre: 'pantry' }
    ],
    timeMinutes: 90,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'beef',
    priceLevel: '$$',
    difficulty: 'medium',
    timeIntensity: 'long',
    dishType: 'main',
    recommendedSideMealIds: ['seasonal-berry-salad'],
    recommendedSideExtraIngredients: [
      { name: 'stuffing mix', unit: 'unit', amount: 1, genre: 'pantry' }
    ]
  },
  {
    id: 'stuffed-peppers',
    name: 'Stuffed Pepper Slices',
    description: 'Stuffed bell pepper slices with rice, ground beef, and cheese',
    ingredients: [
      { name: 'bell peppers', unit: 'unit', amount: 4, genre: 'produce' },
      { name: 'ground beef', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'rice', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: 'colby jack cheese', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'el pato tomato sauce', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'taco seasoning packet', unit: 'unit', amount: 1, genre: 'pantry' }
    ],
    timeMinutes: 30,
    multitaskable: false,
    cuisine: 'American',
    meatType: 'beef',
    priceLevel: '$$',
    difficulty: 'medium',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: ['elote'],
    recommendedSideExtraIngredients: [
      { name: 'refried beans', unit: 'oz', amount: 7, genre: 'pantry' }
    ]
  },
  {
    id: 'sloppy-joses',
    name: 'Sloppy Joses',
    description: 'Spicy sloppy Joes with jalapenos and spicy pickles',
    ingredients: [
      { name: 'ground beef', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'manwich sauce', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'pickled jalapenos', unit: 'oz', amount: 1.5, genre: 'pantry' },
      { name: 'spicy pickles', unit: 'unit', amount: 0.25, genre: 'pantry' },
      { name: 'hamburger buns', unit: 'unit', amount: 1, genre: 'bakery' }
    ],
    timeMinutes: 20,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'beef',
    priceLevel: '$$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: [ 'bbq-beans', 'seasonal-berry-salad', 'mac-and-cheese', 'deviled-eggs' ],
    recommendedSideExtraIngredients: [
      { name: 'fries', unit: 'unit', amount: 1, genre: 'frozen' },
      { name: 'tots', unit: 'unit', amount: 1, genre: 'frozen' },
      { name: 'onion rings', unit: 'unit', amount: 1, genre: 'frozen' },
      { name: 'baked beans', unit: 'oz', amount: 7, genre: 'pantry' }
    ]
  },
  {
    id: 'salmon-blts',
    name: 'Salmon BLTs',
    description: 'Salmon sandwiches with lettuce, tomato, and bacon',
    ingredients: [
      { name: 'salmon', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'lettuce', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'tomato', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'avocado', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'bacon', unit: 'unit', amount: 1, genre: 'deli' },
      { name: 'mayonnaise', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'hamburger buns', unit: 'unit', amount: 1, genre: 'bakery' }
    ],
    timeMinutes: 30,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'seafood',
    priceLevel: '$$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: ['bbq-beans', 'deviled-eggs'],
    recommendedSideExtraIngredients: [
      { name: 'fries', unit: 'unit', amount: 1, genre: 'frozen' }
    ]
  },
  {
    id: 'chicago-hot-dog',
    name: 'Chicago Hot Dog',
    description: 'Chicago hot dog with peppers, onions, pickles, tomatoes, and mustard',
    ingredients: [
      { name: 'hot dogs', unit: 'unit', amount: 1, genre: 'deli' },
      { name: 'spicy pickles', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.25, genre: 'produce' },
      { name: 'peperoncino peppers', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'tomato', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'poupon mustard', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'celery salt', unit: 'tsp', amount: 0.25, genre: 'pantry' },
      { name: 'poppy seeds', unit: 'tsp', amount: 0.25, genre: 'pantry' },
      { name: 'hot dog buns', unit: 'unit', amount: 1, genre: 'bakery' }
    ],
    timeMinutes: 30,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'beef',
    priceLevel: '$$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: ['bbq-beans'],
    recommendedSideExtraIngredients: [
      { name: 'baked beans', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'onion rings', unit: 'unit', amount: 1, genre: 'frozen' },
      { name: 'fries', unit: 'unit', amount: 1, genre: 'frozen' },
      { name: 'tots', unit: 'unit', amount: 1, genre: 'frozen' }
    ]
  },
  {
    id: 'bbq-beans',
    name: 'BBQ Beans',
    description: 'BBQ beans with celery, jalapeno, and beef smokies',
    ingredients: [
      { name: 'pinto beans', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'chili beans', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'beef smokies', unit: 'unit', amount: 1, genre: 'deli' },
      { name: 'celery', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'jalapeno peppers', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.25, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'brown sugar', unit: 'cup', amount: 0.25, genre: 'pantry' },
      { name: 'ketchup', unit: 'cup', amount: 0.25, genre: 'pantry' },
      { name: 'poupon mustard', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'worcestershire sauce', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'chipotle peppers', unit: 'oz', amount: 1.5, genre: 'pantry' },
      { name: 'dried chilies', unit: 'tbsp', amount: 0.5, genre: 'spices' },
      { name: 'molasses', unit: 'tbsp', amount: 1, genre: 'baking' }
    ],
    timeMinutes: 30,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'beef',
    priceLevel: '$$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side'
  },
  {
    id: 'mashed-potatoes',
    name: 'Mashed Potatoes',
    description: 'Creamy mashed potatoes with butter and milk',
    ingredients: [
      { name: 'potatoes', unit: 'unit', amount: 4, genre: 'produce' },
      { name: 'butter', unit: 'tbsp', amount: 8, genre: 'dairy' },
      { name: 'milk', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'sour cream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'gravy mix', unit: 'unit', amount: 1, genre: 'pantry' }
    ],
    timeMinutes: 30,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side'
  },
  {
    id: 'kosheri-with-meat',
    name: 'Kosheri with Meat',
    description: 'Kosheri (spicy lentil rice pasta) with tomato sauce, meat, and onions',
    ingredients: [
      { name: 'rice', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: 'lentils', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: 'ground beef', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'chickpeas', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'macaroni', unit: 'unit', amount: 0.5, genre: 'pantry' },
      { name: 'diced tomatoes', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'tomato paste', unit: 'oz', amount: 3.5, genre: 'pantry' },
      { name: 'garlic', unit: 'clove', amount: 4, genre: 'produce' },
      { name: 'coriander', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'cumin', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'allspice', unit: 'tsp', amount: 0.25, genre: 'spices' },
      { name: 'cinnamon', unit: 'tsp', amount: 0.5, genre: 'spices' },
      { name: 'paprika', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'fennel seeds', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'chili powder', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'crispy onions', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'olive oil', unit: 'tbsp', amount: 8, genre: 'pantry' },
      { name: 'chili oil', unit: 'tbsp', amount: 1, genre: 'international' }
    ],
    timeMinutes: 60,
    multitaskable: false,
    cuisine: 'Egyptian',
    meatType: 'beef',
    priceLevel: '$$',
    difficulty: 'medium',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: ['fatoush-salad'],
    recommendedSideExtraIngredients: [
      { name: 'olives', unit: 'oz', amount: 3.5, genre: 'pantry' }
    ]
  },
  {
    id: 'korean-beef',
    name: 'Korean Beef',
    description: 'Korean beef with rice, lettuce, and green onions',
    ingredients: [
      { name: 'ground beef', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'rice', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: 'lettuce', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'green onions', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'soy sauce', unit: 'tbsp', amount: 0.5, genre: 'pantry' },
      { name: 'teriyaki sauce', unit: 'tbsp', amount: 0.5, genre: 'pantry' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'ginger paste', unit: 'tbsp', amount: 1, genre: 'produce' },
      { name: 'sesame oil', unit: 'tbsp', amount: 0.5, genre: 'pantry' },
      { name: 'sesame seeds', unit: 'tbsp', amount: 0.5, genre: 'pantry' },
      { name: 'brown sugar', unit: 'tbsp', amount: 3, genre: 'baking' },
      { name: 'thai chilies', unit: 'unit', amount: 3, genre: 'pantry' },
      { name: 'siracha', unit: 'tbsp', amount: 0.5, genre: 'international' },
      { name: 'cilantro', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'msg', unit: 'tsp', amount: 1, genre: 'international' }
    ],
    timeMinutes: 30,
    multitaskable: false,
    cuisine: 'Asian',
    meatType: 'beef',
    priceLevel: '$$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: [],
    recommendedSideExtraIngredients: [
      { name: 'kimchi', unit: 'oz', amount: 3, genre: 'pantry' }
    ]
  },
  {
    id: 'pork-ramen',
    name: 'Pork Ramen',
    description: 'Pork ramen with noodles, pork belly, soft boiled egg, mushrooms, and vegetables',
    ingredients: [
      { name: 'ramen noodles', unit: 'unit', amount: 1, genre: 'international' },
      { name: 'pork belly', unit: 'lb', amount: 1, genre: 'international' },
      { name: 'eggs', unit: 'unit', amount: 4, genre: 'dairy' },
      { name: 'bok choy', unit: 'unit', amount: 0.5, genre: 'international' },
      { name: 'green onions', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'soy sauce', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'carrots', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'shiitake mushrooms', unit: 'unit', amount: 1, genre: 'international' },
      { name: 'nori', unit: 'unit', amount: 1, genre: 'international' },
      { name: 'siracha', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'fish sauce', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'tankatsu pork stock', unit: 'tbsp', amount: 3, genre: 'international' },
      { name: 'msg', unit: 'tsp', amount: 1, genre: 'international' }
    ],
    timeMinutes: 50,
    multitaskable: false,
    cuisine: 'Asian',
    meatType: 'pork',
    priceLevel: '$$$',
    difficulty: 'medium',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: [ 'bao-buns' ],
    recommendedSideExtraIngredients: [
      { name: 'gyoza', unit: 'unit', amount: 1, genre: 'deli' }
    ]
  },
  {
    id: 'thai-red-curry',
    name: 'Thai Red Curry',
    description: 'Thai red curry with chicken, zucchini, and bell peppers',
    ingredients: [
      { name: 'chicken breast', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'zucchini', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'bell peppers', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'red chilies', unit: 'unit', amount: 6, genre: 'international' },
      { name: 'garlic', unit: 'clove', amount: 4, genre: 'produce' },
      { name: 'coconut milk', unit: 'oz', amount: 14, genre: 'international' },
      { name: 'fish sauce', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'brown fish paste', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'shrimp paste', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'ginger paste', unit: 'tbsp', amount: 1, genre: 'produce' },
      { name: 'lemongrass', unit: 'unit', amount: 0.5, genre: 'international' },
      { name: 'cilantro', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'shallots', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'corriander', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'cumin', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'lime', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'rice', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: 'msg', unit: 'tsp', amount: 1, genre: 'international' }
    ],
    timeMinutes: 60,
    multitaskable: false,
    cuisine: 'Asian',
    meatType: 'chicken',
    priceLevel: '$$',
    difficulty: 'hard',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: [],
    recommendedSideExtraIngredients: [
      { name: 'gyoza', unit: 'unit', amount: 1, genre: 'deli' }
    ]
  },
  {
    id: 'thai-green-curry',
    name: 'Thai Green Curry',
    description: 'Thai green basil curry with chicken, bamboo shoots, and vegetables',
    ingredients: [
      { name: 'chicken breast', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'bamboo shoots', unit: 'oz', amount: 7, genre: 'international' },
      { name: 'green beans', unit: 'lb', amount: 1.5, genre: 'produce' },
      { name: 'cilantro', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'asian eggplant', unit: 'unit', amount: 2, genre: 'international'},
      { name: 'thai basil leaves', unit: 'unit', amount: 1, genre: 'international' },
      { name: 'coriander leaves', unit: 'unit', amount: 0.5, genre: 'international' },
      { name: 'thai chilies', unit: 'unit', amount: 6, genre: 'international' },
      { name: 'garlic', unit: 'clove', amount: 4, genre: 'produce' },
      { name: 'lemongrass', unit: 'unit', amount: 0.5, genre: 'international' },
      { name: 'lime leaves', unit: 'unit', amount: 0.5, genre: 'international' },
      { name: 'lime', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'fish sauce', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'brown fish paste', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'shrimp paste', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'coconut milk', unit: 'oz', amount: 14, genre: 'international' },
      { name: 'olive oil', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'shallots', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'ginger paste', unit: 'tbsp', amount: 0.5, genre: 'produce' },
      { name: 'msg', unit: 'tsp', amount: 1, genre: 'international' },
      { name: 'rice', unit: 'cup', amount: 1, genre: 'pantry' }
    ],
    timeMinutes: 60,
    multitaskable: false,
    cuisine: 'Asian',
    meatType: 'chicken',
    priceLevel: '$$',
    difficulty: 'hard',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: [],
    recommendedSideExtraIngredients: [
      {name: 'gyoza', unit: 'unit', amount: 1, genre: 'deli' }
    ]
  },
  {
    id: 'bao-buns',
    name: 'Bao Buns',
    description: 'Steamed bao buns with shredded bbq pork',
    ingredients: [
      { name: 'flour', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'yeast', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'sugar', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'olive oil', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'pulled pork', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'green onions', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'sesame seeds', unit: 'tbsp', amount: 0.5, genre: 'spices' },
      { name: 'soy sauce', unit: 'tbsp', amount: 0.5, genre: 'pantry' },
      { name: 'sesame oil', unit: 'tsp', amount: 1, genre: 'international' },
      { name: 'bbq sauce', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'siracha', unit: 'tbsp', amount: 0.5, genre: 'international' }
    ],
    timeMinutes: 30,
    multitaskable: false,
    cuisine: 'Asian',
    meatType: 'pork',
    priceLevel: '$',
    difficulty: 'medium',
    timeIntensity: 'quick',
    dishType: 'side',
    extraType: 'snack'
  },
  {
    id: 'yellow-curry',
    name: 'Yellow Tumeric Curry',
    description: 'Yellow tumeric coconut curry with chicken, potatoes, and carrots',
    ingredients: [
      { name: 'chicken breast', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'potatoes', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'carrots', unit: 'unit', amount: 3, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'coconut milk', unit: 'oz', amount: 14, genre: 'pantry' },
      { name: 'chicken stock', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'ginger paste', unit: 'tbsp', amount: 1, genre: 'produce' },
      { name: 'shallots', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'thai chilies', unit: 'unit', amount: 2, genre: 'international' },
      { name: 'dried red chilies', unit: 'unit', amount: 3, genre: 'international' },
      { name: 'shredded coconut', unit: 'cup', amount: 0.25, genre: 'baking' },
      { name: 'siracha', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'dates', unit: 'tbsp', amount: 2, genre: 'international' },
      { name: 'tamarind', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'tumeric', unit: 'tbsp', amount: 0.5, genre: 'spices' },
      { name: 'cumin', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'anise or fennel seeds', unit: 'tsp', amount: 1, genre: 'international' },
      { name: 'chili powder', unit: 'tsp', amount: 1, genre: 'pantry' },
      { name: 'cardamom pods', unit: 'unit', amount: 3, genre: 'international' },
      { name: 'curry leaves (bay leaves)', unit: 'unit', amount: 3, genre: 'international' },
      { name: 'brown sugar', unit: 'tbsp', amount: 1, genre: 'baking' },
      { name: 'rice', unit: 'cup', amount: 1, genre: 'pantry' }
    ],
    timeMinutes: 40,
    multitaskable: false,
    cuisine: 'Indian',
    meatType: 'chicken',
    priceLevel: '$$',
    difficulty: 'medium',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: [ 'fatoush-salad' ],
    recommendedSideExtraIngredients: [
      { name: 'gyoza', unit: 'unit', amount: 1, genre: 'deli' },
      { name: 'naan (flatbread)', unit: 'unit', amount: 0.5, genre: 'international' },
      { name: 'dawn paratha (flaky flatbread)', unit: 'unit', amount: 0.25, genre: 'international' }
    ]
  },
  {
    id: 'gumbo',
    name: 'Gumbo',
    description: 'Gumbo with chicken, shrimp, sausage, okra, and rice',
    ingredients: [
      { name: 'rotisserie chicken', unit: 'unit', amount: 0.5, genre: 'butchery' },
      { name: 'shrimp', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'andouille sausage', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'okra', unit: 'cup', amount: 1, genre: 'frozen' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'bell pepper', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'beef stock', unit: 'cup', amount: 2, genre: 'pantry' },
      { name: 'tapatio', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'cajun seasoning', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'curry leaves (bay leaves)', unit: 'unit', amount: 1, genre: 'international' },
      { name: 'crab', unit: 'oz', amount: 3.5, genre: 'pantry' },
      { name: 'bacon grease', unit: 'tbsp', amount: 4, genre: 'pantry' },
      { name: 'flour', unit: 'cup', amount: 0.25, genre: 'baking' },
      { name: 'tomato sauce', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'worcestershire sauce', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'apple cider vinegar', unit: 'tbsp', amount: 1, genre: 'pantry' }
    ],
    timeMinutes: 60,
    multitaskable: false,
    cuisine: 'American',
    meatType: 'chicken',
    priceLevel: '$$',
    difficulty: 'hard',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: [ 'seasonal-berry-salad'],
    recommendedSideExtraIngredients: [
      { name: 'rice', unit: 'cup', amount: 1, genre: 'pantry' }
    ]
  },
  {
    id: 'chicken-tikka-masala',
    name: 'Chicken Tikka Masala',
    description: 'Creamy chicken tikka masala with rice and cilantro',
    ingredients: [
      { name: 'rotisserie chicken', unit: 'unit', amount: 1, genre: 'butchery' },
      { name: 'rice', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'tomato sauce', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'tomato paste', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'heavy whippingcream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'sadaf tikka masala seasoning', unit: 'oz', amount: 1, genre: 'international' },
      { name: 'cilantro', unit: 'unit', amount: 1, genre: 'produce' }
    ],
    timeMinutes: 40,
    multitaskable: true,
    cuisine: 'Indian',
    meatType: 'chicken',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: [ 'daal','chana-masala'],
    recommendedSideExtraIngredients: [
      { name: 'dawn paratha (flaky flatbread)', unit: 'unit', amount: 0.25, genre: 'international' },
      { name: 'naan (flatbread)', unit: 'unit', amount: 0.5, genre: 'international' }
    ]
  },
  {
    id: 'daal',
    name: 'Daal',
    description: 'Thick Indian lentil soup with cumin seed, mustard seed, and cilantro',
    ingredients: [
      { name: 'yellow lentils', unit: 'cup', amount: 1, genre: 'international' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'cumin seed', unit: 'tsp', amount: 1, genre: 'international' },
      { name: 'black mustard seed', unit: 'tsp', amount: 1, genre: 'international' },
      { name: 'cilantro', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'chicken stock', unit: 'cup', amount: 2, genre: 'pantry' },
      { name: 'jalapeno', unit: 'unit', amount: 1, genre: 'produce' }
    ],
    timeMinutes: 40,
    multitaskable: true,
    cuisine: 'Indian',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side'
  },
  {
    id: 'chana-masala',
    name: 'Chana Masala',
    description: 'Spicy Indian chickpea curry with tomato sauce, onions, and cilantro',
    ingredients: [
      { name: 'chickpeas', unit: 'oz', amount: 14, genre: 'pantry' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'apple cider vinegar', unit: 'tbsp', amount: 0.5, genre: 'pantry' },
      { name: 'olive oil', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'el pato tomato sauce', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'cilantro', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'chicken stock', unit: 'cup', amount: 0.5, genre: 'pantry' },
      { name: 'jalapeno', unit: 'unit', amount: 2, genre: 'produce' },
      { name: 'cumin', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'coriander', unit: 'tsp', amount: 1, genre: 'spices' }
    ],
    timeMinutes: 40,
    multitaskable: false,
    cuisine: 'Indian',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side',
    extraType: 'snack'
  },
  {
    id: 'chicken-chana',
    name: 'Chicken Poori Chana',
    description: 'Spicy Indian chickpea curry with chicken and flaky flatbread',
    ingredients: [
      { name: 'rotisserie chicken', unit: 'unit', amount: 0.5, genre: 'butchery' },
      { name: 'chickpeas', unit: 'oz', amount: 14, genre: 'pantry' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'apple cider vinegar', unit: 'tbsp', amount: 0.5, genre: 'pantry' },
      { name: 'olive oil', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'el pato tomato sauce', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'cilantro', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'chicken stock', unit: 'cup', amount: 0.5, genre: 'pantry' },
      { name: 'jalapeno', unit: 'unit', amount: 2, genre: 'produce' },
      { name: 'cumin', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'coriander', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'dawn paratha (flaky flatbread)', unit: 'unit', amount: 0.25, genre: 'international' }
    ],
    timeMinutes: 40,
    multitaskable: false,
    cuisine: 'Indian',
    meatType: 'chicken',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: [ ],
    recommendedSideExtraIngredients: [
      { name: 'rice', unit: 'cup', amount: 1, genre: 'pantry' }
    ]
  },
  {
    id: 'southwest-chili',
    name: 'Southwest Chili',
    description: 'Southwest chili with beef, beans, corn, and tomatoes',
    ingredients: [
      { name: 'ground beef', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'ranch style beans with jalapeno', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'black beans', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'corn', unit: 'cup', amount: 1, genre: 'frozen' },
      { name: 'diced tomatoes', unit: 'oz', amount: 7, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'bell pepper', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'chili powder', unit: 'tbsp', amount: 1, genre: 'spices' },
      { name: 'seasoned salt', unit: 'tbsp', amount: 0.5, genre: 'spices' },
      { name: 'v8 vegetable juicy spicy juice', unit: 'oz', amount: 12, genre: 'international' },
      { name: 'cheddar cheese', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'sour cream', unit: 'cup', amount: 0.5, genre: 'dairy' }
    ],
    timeMinutes: 40,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'beef',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: [ 'cornbread-cake'],
    recommendedSideExtraIngredients: [
      { name: 'corn chips', unit: 'unit', amount: 1, genre: 'snacks' }
    ]
  },
  {
    id: 'cornbread-cake',
    name: 'Cornbread Cake',
    description: 'Fluffy cornbread made with honey',
    ingredients: [
      { name: 'cornmeal', unit: 'cup', amount: 0.5, genre: 'baking' },
      { name: 'flour', unit: 'cup', amount: 1.5, genre: 'baking' },
      { name: 'sugar', unit: 'cup', amount: 0.0625, genre: 'baking' },
      { name: 'baking powder', unit: 'tbsp', amount: 1, genre: 'baking' },
      { name: 'vegetable oil', unit: 'cup', amount: 0.33, genre: 'pantry' },
      { name: 'butter', unit: 'tbsp', amount: 3, genre: 'dairy' },
      { name: 'honey', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'eggs', unit: 'unit', amount: 2, genre: 'dairy' },
      { name: 'milk', unit: 'cup', amount: 1.25, genre: 'dairy' }
    ],
    timeMinutes: 50,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side'  
  },
  {
    id: 'chicken-noodle-soup',
    name: 'Chicken Noodle Soup',
    description: 'Chicken noodle soup with carrots and celery',
    ingredients: [
      { name: 'rotisserie chicken', unit: 'unit', amount: 1, genre: 'butchery' },
      { name: 'extra wide egg noodles', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'carrots', unit: 'unit', amount: 4, genre: 'produce' },
      { name: 'celery', unit: 'unit', amount: 4, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'chicken stock', unit: 'cup', amount: 4, genre: 'pantry' }
    ],
    timeMinutes: 30,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'chicken',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: [ 'ceaser-salad' ],
    recommendedSideExtraIngredients: [
      { name: 'yeast rolls', unit: 'unit', amount: 1, genre: 'frozen' }
    ]
  },
  {
    id: 'potato-soup',
    name: 'Cheesy Ham Potato Soup',
    description: 'Cheesy ham potato soup with onion and bacon',
    ingredients: [
      { name: 'ham', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'bacon', unit: 'lb', amount: 1, genre: 'deli' },
      { name: 'potatoes', unit: 'unit', amount: 3, genre: 'produce' },
      { name: 'cream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'milk', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'cheddar cheese', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'chicken stock', unit: 'cup', amount: 2, genre: 'pantry' },
      { name: 'green onions', unit: 'unit', amount: 0.5, genre: 'produce' }
    ],
    timeMinutes: 40,
    multitaskable: false,
    cuisine: 'American',
    meatType: 'pork',
    priceLevel: '$$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: [ ],
    recommendedSideExtraIngredients: [
      { name: 'yeast rolls', unit: 'unit', amount: 0.25, genre: 'frozen' }
    ]
  },
  {
    id: 'chicken-and-dumplings',
    name: 'Chicken and Dumplings',
    description: 'Chicken and dumpling soup with carrots, potatoes, and celery',
    ingredients: [
      { name: 'rotisserie chicken', unit: 'unit', amount: 0.5, genre: 'butchery' },
      { name: 'carrots', unit: 'unit', amount: 2, genre: 'produce' },
      { name: 'celery', unit: 'unit', amount: 3, genre: 'produce' },
      { name: 'potatoes', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'chicken stock', unit: 'cup', amount: 3, genre: 'pantry' },
      { name: 'heavy whipping cream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'milk', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'thyme', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'flour', unit: 'cup', amount: 0.5, genre: 'baking' },
      { name: 'shortening', unit: 'tbsp', amount: 3, genre: 'baking' },
      { name: 'baking powder', unit: 'tsp', amount: 1, genre: 'baking' }
    ],
    timeMinutes: 50,
    multitaskable: false,
    cuisine: 'American',
    meatType: 'chicken',
    priceLevel: '$',
    difficulty: 'medium',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: [ 'ceaser-salad' ],
    recommendedSideExtraIngredients: [ ]
  },
  {
    id: 'minestrone',
    name: 'Chicken Minestrone',
    description: 'Italian veggie soup with beans and noodles',
    ingredients: [
      { name: 'rotisserie chicken', unit: 'unit', amount: 0.5, genre: 'butchery' },
      { name: 'diced tomatoes', unit: 'oz', amount: 7, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'zuchini', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'carrots', unit: 'unit', amount: 2, genre: 'produce' },
      { name: 'celery', unit: 'unit', amount: 3, genre: 'produce' },
      { name: 'kidney beans', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'chicken stock', unit: 'cup', amount: 3, genre: 'pantry' },
      { name: 'tortellini', unit: 'oz', amount: 7, genre: 'pantry' },
      { name: 'spinach', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'parmesan cheese', unit: 'cup', amount: 0.5, genre: 'deli' }
    ],
    timeMinutes: 20,
    multitaskable: false,
    cuisine: 'Italian',
    meatType: 'chicken',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: [ 'ceaser-salad' ],
    recommendedSideExtraIngredients: [
      { name: 'yeast rolls', unit: 'unit', amount: 0.25, genre: 'frozen' }
    ]
  },
  {
    id: 'italian-sausage-soup',
    name: 'Italian Sausage Soup',
    description: 'Italian sausage soup with kale and potatoes',
    ingredients: [
      { name: 'hot italian sausage', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'kale', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'potatoes', unit: 'unit', amount: 2, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'chicken stock', unit: 'cup', amount: 3, genre: 'pantry' },
      { name: 'milk', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'heavy whipping cream', unit: 'cup', amount: 0.75, genre: 'dairy' },
      { name: 'oregano', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'thyme', unit: 'tsp', amount: 1, genre: 'spices' }
    ],
    timeMinutes: 40,
    multitaskable: false,
    cuisine: 'Italian',
    meatType: 'pork',
    priceLevel: '$$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: [ 'ceaser-salad' ],
    recommendedSideExtraIngredients: [
      { name: 'yeast rolls', unit: 'unit', amount: 0.25, genre: 'frozen' },
      { name: 'french bread', unit: 'unit', amount: 0.5, genre: 'bakery' },
      { name: 'bread sticks', unit: 'unit', amount: 1, genre: 'frozen' }
     ]
  },
  {
    id: 'guacamole-snack',
    name: 'Guacamole',
    description: 'Creamy avocado dip with lime and pomegranate',
    ingredients: [
      { name: 'avocado', unit: 'unit', amount: 3, genre: 'produce' },
      { name: 'lime', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'onion (red)', unit: 'unit', amount: 0.25, genre: 'produce' },
      { name: 'pomegranate seeds', unit: 'cup', amount: 0.25, genre: 'produce' },
      { name: 'jalapeno', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 1, genre: 'produce' },
      { name: 'cilantro', unit: 'unit', amount: 0.25, genre: 'produce' }
    ],
    timeMinutes: 10,
    multitaskable: false,
    cuisine: 'Mexican',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side',
    extraType: 'snack'
  },
  {
    id: 'red-salsa',
    name: 'Red Salsa',
    description: 'Red salsa with cilantro and jalapeno',
    ingredients: [
      { name: 'diced tomatoes', unit: 'oz', amount: 14, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.25, genre: 'produce' },
      { name: 'jalapeno', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'cilantro', unit: 'unit', amount: 0.25, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 1, genre: 'produce' },
      { name: 'lime', unit: 'unit', amount: 1, genre: 'produce' }
    ],
    timeMinutes: 10,
    multitaskable: false,
    cuisine: 'Mexican',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side',
    extraType: 'snack'
  },
  {
    id: 'huevos-rancheros',
    name: 'Huevos Rancheros',
    description: 'Green chili eggs with cheese, hashbrowns, and tortillas',
    ingredients: [
      { name: 'eggs', unit: 'unit', amount: 4, genre: 'dairy' },
      { name: '505 green chili sauce', unit: 'oz', amount: 3, genre: 'pantry' },
      { name: 'cheddar cheese', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'hashbrowns', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: 'guerrero rousimas tortillas', unit: 'unit', amount: 4, genre: 'pantry' }
    ],
    timeMinutes: 20,
    multitaskable: false,
    cuisine: 'Mexican',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side',
    extraType: 'breakfast'
  },
  {
    id: 'chicken-pot-pie',
    name: 'Chicken Pot Pie',
    description: 'Chicken pot pie with carrots, potatoes, and celery',
    ingredients: [
      { name: 'rotisserie chicken', unit: 'unit', amount: 1, genre: 'butchery' },
      { name: 'carrots', unit: 'unit', amount: 4, genre: 'produce' },
      { name: 'potatoes', unit: 'unit', amount: 2, genre: 'produce' },
      { name: 'celery', unit: 'unit', amount: 6, genre: 'produce' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'peas', unit: 'cup', amount: 0.5, genre: 'frozen' },
      { name: 'heavy whipping cream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'milk', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'thyme', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'flour', unit: 'cup', amount: 0.25, genre: 'baking' },
      { name: 'butter', unit: 'tbsp', amount: 4, genre: 'dairy' },
      { name: 'pie crust', unit: 'unit', amount: 2, genre: 'dairy' },
      { name: 'eggs', unit: 'unit', amount: 1, genre: 'dairy' }
    ],
    timeMinutes: 50,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'chicken',
    priceLevel: '$$',
    difficulty: 'medium',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: ['seasonal-berry-salad'],
    recommendedSideExtraIngredients: [ ]
  },
  {
    id: 'french-dips',
    name: 'French Dips',
    description: 'Toasted roast beef sandwich with cheese, mushrooms, and onions',
    ingredients: [
      { name: 'roast beef', unit: 'lb', amount: 1, genre: 'deli' },
      { name: 'sliced provolone cheese', unit: 'unit', amount: 1, genre: 'deli' },
      { name: 'mushrooms', unit: 'cup', amount: 1, genre: 'produce' },
      { name: 'onions', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'bread rolls', unit: 'unit', amount: 6, genre: 'bakery' },
      { name: 'beef stock', unit: 'cup', amount: 2, genre: 'pantry' },
      { name: 'butter', unit: 'tbsp', amount: 4, genre: 'dairy' }
    ],
    timeMinutes: 20,
    multitaskable: false,
    cuisine: 'American',
    meatType: 'beef',
    priceLevel: '$$$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: ['seasonal-berry-salad'],
    recommendedSideExtraIngredients: [ 
      { name: 'fries', unit: 'unit', amount: 1, genre: 'frozen' }
     ]
  },
  {
    id: 'fruit-smoothie-beverage',
    name: 'Fruit Smoothie',
    description: 'Blend of berries, banana, and yogurt',
    ingredients: [
      { name: 'frozen berries', unit: 'cup', amount: 2, genre: 'frozen' },
      { name: 'banana', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'honey', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'milk', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'yogurt', unit: 'cup', amount: 1, genre: 'dairy' }
    ],
    timeMinutes: 5,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'dessert',
    extraType: 'beverages'
  },
  {
    id: 'chicken-stir-fry',
    name: 'Chicken Stir-fry',
    description: 'Noodle chicken stir-fry with vegetables',
    ingredients: [
      { name: 'chicken breast', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'broccoli', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'bell pepper', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'carrots', unit: 'unit', amount: 2, genre: 'produce' },
      { name: 'mushrooms', unit: 'cup', amount: 1, genre: 'produce' },
      { name: 'snow peas', unit: 'cup', amount: 1, genre: 'produce' },
      { name: 'bean sprouts', unit: 'cup', amount: 1, genre: 'international' },
      { name: 'onion (brown or white)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'soy sauce', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'teriyaki sauce', unit: 'tbsp', amount: 2, genre: 'international' },
      { name: 'siracha', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'garlic', unit: 'clove', amount: 2, genre: 'produce' },
      { name: 'ginger', unit: 'tsp', amount: 1, genre: 'produce' },
      { name: 'olive oil', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'brown fish paste', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'msg', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'rice noodles', unit: 'unit', amount: 1, genre: 'international' },
      { name: 'sweet chili sauce', unit: 'tbsp', amount: 1, genre: 'international' }
    ],
    timeMinutes: 25,
    multitaskable: true,
    cuisine: 'Asian',
    meatType: 'chicken',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: ['bao'],
    recommendedSideExtraIngredients: [
      { name: 'gyoza', unit: 'unit', amount: 1, genre: 'international' }
    ]
  },
  {
    id: 'caesar-salad',
    name: 'Caesar Salad',
    description: 'Crisp romaine with creamy dressing and croutons',
    ingredients: [
      { name: 'lettuce', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'croutons', unit: 'cup', amount: 1, genre: 'bakery' },
      { name: 'grated parmesan cheese', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'caesar dressing', unit: 'cup', amount: 0.5, genre: 'deli' }
    ],
    timeMinutes: 10,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side'
  },
  {
    id: 'beef-tacos',
    name: 'Beef Tacos',
    description: 'Seasoned beef with toppings in a crunchy shell',
    ingredients: [
      { name: 'ground beef', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'taco shells', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'taco seasoning', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'lettuce', unit: 'cup', amount: 2, genre: 'produce' },
      { name: 'tomato', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'cilantro', unit: 'cup', amount: 1, genre: 'produce' },
      { name: 'lime', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'sour cream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'cheddar cheese', unit: 'cup', amount: 0.5, genre: 'dairy' }
    ],
    timeMinutes: 25,
    multitaskable: true,
    cuisine: 'Mexican',
    meatType: 'beef',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: ['elote','spanish-rice','guacamole-snack','red-salsa'],
    recommendedSideExtraIngredients: [ 
      { name: 'refried beans', unit: 'cup', amount: 1, genre: 'international' }
     ]
  },
  {
    id: 'chocolate-chip-cookies',
    name: 'Chocolate Chip Cookies',
    description: 'Chewy cookies loaded with chocolate chips',
    ingredients: [
      { name: 'flour', unit: 'cup', amount: 2.5, genre: 'baking' },
      { name: 'butter', unit: 'tbsp', amount: 8, genre: 'dairy' },
      { name: 'sugar', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'brown sugar', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'eggs', unit: 'unit', amount: 2, genre: 'dairy' },
      { name: 'vanilla extract', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'baking soda', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'chocolate chips', unit: 'cup', amount: 2, genre: 'baking' }
    ],
    timeMinutes: 20,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'medium',
    dishType: 'dessert',
    extraType: 'snack'
  },
  {
    id: 'cinnamon-rolls',
    name: 'Cinnamon Rolls',
    description: 'Soft cinnamon rolls with cream cheese frosting',
    ingredients: [
      { name: 'flour', unit: 'cup', amount: 2.5, genre: 'baking' },
      { name: 'butter', unit: 'tbsp', amount: 16, genre: 'dairy' },
      { name: 'brown sugar', unit: 'cup', amount: 2, genre: 'baking' },
      { name: 'sugar', unit: 'cup', amount: 0.5, genre: 'baking' },
      { name: 'yeast', unit: 'tsp', amount: 4, genre: 'pantry' },
      { name: 'eggs', unit: 'unit', amount: 2, genre: 'dairy' },
      { name: 'milk', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'cinnamon', unit: 'tsp', amount: 12, genre: 'spices' },
      { name: 'cream cheese', unit: 'tbsp', amount: 16, genre: 'dairy' },
      { name: 'vanilla extract', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'powdered sugar', unit: 'cup', amount: 2, genre: 'pantry' }
    ],
    timeMinutes: 300,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'medium',
    timeIntensity: 'long',
    dishType: 'dessert',
    extraType: 'breakfast'
  },
  {
    id: 'donuts',
    name: 'Homemade Donuts',
    description: 'Fried donuts with powdered sugar',
    ingredients: [
      { name: 'flour', unit: 'cup', amount: 2.25, genre: 'baking' },
      { name: 'powdered sugar', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'vegetable oil', unit: 'cup', amount: 2, genre: 'pantry' },
      { name: 'eggs', unit: 'unit', amount: 1, genre: 'dairy' },
      { name: 'baking soda', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'sour cream', unit: 'cup', amount: 1, genre: 'dairy' }
    ],
    timeMinutes: 20,
    multitaskable: false,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'dessert',
    extraType: 'snack'
  },
  {
    id: 'peanut-butter-brownies',
    name: 'Peanut Butter Brownies',
    description: 'Rich brownies with peanut butter candy',
    ingredients: [
      { name: 'flour', unit: 'cup', amount: 2, genre: 'baking' },
      { name: 'vegetable oil', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'sugar', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'cocoa powder', unit: 'cup', amount: 0.5, genre: 'baking' },
      { name: 'baking powder', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'vanilla extract', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'peanut butter m&ms', unit: 'cup', amount: 1, genre: 'snacks' }
    ],
    timeMinutes: 30,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'dessert',
    extraType: 'snack'
  },
  {
    id: 'oatmeal-cookies',
    name: 'Oatmeal Cookies',
    description: 'Oatmeal cookies with raisins',
    ingredients: [
      { name: 'quick oats', unit: 'cup', amount: 2, genre: 'pantry' },
      { name: 'butter', unit: 'tbsp', amount: 8, genre: 'dairy' },
      { name: 'sugar', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'flour', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'brown sugar', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'eggs', unit: 'unit', amount: 2, genre: 'dairy' },
      { name: 'baking soda', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'vanilla extract', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'raisins', unit: 'cup', amount: 1, genre: 'produce' }
    ],
    timeMinutes: 20,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'dessert',
    extraType: 'snack'
  },
  { 
    id: 'molasses-cookies',
    name: 'Molasses Cookies',
    description: 'Chewy molasses crinkle cookies (a family recipe)',
    ingredients: [
      { name: 'flour', unit: 'cup', amount: 2.25, genre: 'baking' },
      { name: 'butter', unit: 'tbsp', amount: 4, genre: 'dairy' },
      { name: 'shortening', unit: 'tbsp', amount: 8, genre: 'dairy' },
      { name: 'brown sugar', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'molasses', unit: 'cup', amount: 0.25, genre: 'pantry' },
      { name: 'baking soda', unit: 'tsp', amount: 2, genre: 'baking' },
      { name: 'cinnamon', unit: 'tsp', amount: 1, genre: 'spices' },
      { name: 'cloves', unit: 'tsp', amount: 0.5, genre: 'spices' },
      { name: 'eggs', unit: 'unit', amount: 1, genre: 'dairy' },
      { name: 'ginger', unit: 'tsp', amount: 1, genre: 'spices' }
    ],
    timeMinutes: 20,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'dessert',
    extraType: 'snack'
  },
  {
    id: 'blueberry-muffins',
    name: 'Blueberry Muffins',
    description: 'Moist blueberry muffins with a crumbly top',
    ingredients: [
      { name: 'flour', unit: 'cup', amount: 2, genre: 'baking' },
      { name: 'sugar', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'baking powder', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'baking soda', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'eggs', unit: 'unit', amount: 2, genre: 'dairy' },
      { name: 'buttermilk', unit: 'cup', amount: 1, genre: 'dairy' },
      { name: 'blueberries', unit: 'cup', amount: 1, genre: 'produce' },
      { name: 'butter', unit: 'tbsp', amount: 8, genre: 'dairy' },
      { name: 'vanilla extract', unit: 'tsp', amount: 1, genre: 'baking' }
    ],
    timeMinutes: 20,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'dessert',
    extraType: 'breakfast'
  },
  {
    id: 'chocolate-cherry-muffins',
    name: 'Chocolate Cherry Muffins',
    description: 'Moist double chocolate cherry muffins with a hint of almond',
    ingredients: [
      { name: 'flour', unit: 'cup', amount: 2, genre: 'baking' },
      { name: 'sugar', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'baking powder', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'baking soda', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'cocoa powder', unit: 'cup', amount: 0.5, genre: 'baking' },
      { name: 'eggs', unit: 'unit', amount: 2, genre: 'dairy' },
      { name: 'milk', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'sour cream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'vegetable oil', unit: 'tbsp', amount: 8, genre: 'dairy' },
      { name: 'chocolate chips', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'cherries', unit: 'cup', amount: 1, genre: 'produce' },
      { name: 'almond extract', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'vanilla extract', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'muffin/cupcake liners', unit: 'unit', amount: 1, genre: 'baking' }
    ],
    timeMinutes: 20,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'dessert',
    extraType: 'breakfast'
  },
  {
    id: 'lemon-poppy-seed-muffins',
    name: 'Lemon Poppy Seed Muffins',
    description: 'Moist lemon poppy seed muffins',
    ingredients: [
      { name: 'flour', unit: 'cup', amount: 2, genre: 'baking' },
      { name: 'sugar', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'baking powder', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'baking soda', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'eggs', unit: 'unit', amount: 2, genre: 'dairy' },
      { name: 'milk', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'sour cream', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'lemon juice', unit: 'tbsp', amount: 2, genre: 'produce' },
      { name: 'poppy seeds', unit: 'tbsp', amount: 1, genre: 'baking' },
      { name: 'vegetable oil', unit: 'tbsp', amount: 8, genre: 'dairy' },
      { name: 'vanilla extract', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'muffin/cupcake liners', unit: 'unit', amount: 1, genre: 'baking' }
    ],
    timeMinutes: 20,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'dessert',
    extraType: 'breakfast'
  },
  {
    id: 'banana-bread',
    name: 'Banana Bread',
    description: 'Moist banana bread (a family recipe)',
    ingredients: [
      { name: 'flour', unit: 'cup', amount: 2, genre: 'baking' },
      { name: 'sugar', unit: 'cup', amount: 1, genre: 'baking' },
      { name: 'baking soda', unit: 'tsp', amount: 1, genre: 'baking' },
      { name: 'eggs', unit: 'unit', amount: 2, genre: 'dairy' },
      { name: 'bananas', unit: 'unit', amount: 4, genre: 'produce' },
      { name: 'butter', unit: 'tbsp', amount: 16, genre: 'dairy' },
      { name: 'nuts', unit: 'cup', amount: 1, genre: 'produce' }
    ],
    timeMinutes: 60,
    multitaskable: true,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'medium',
    dishType: 'dessert',
    extraType: 'breakfast'
  },
  {
    id: 'shrimp-fried-rice',
    name: 'Shrimp Fried Rice',
    description: 'Savory fried rice with shrimp and eggs',
    ingredients: [
      { name: 'rice', unit: 'cup', amount: 2, genre: 'pantry' },
      { name: 'shrimp', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'ham', unit: 'lb', amount: 0.5, genre: 'deli' },
      { name: 'peas', unit: 'cup', amount: 1, genre: 'frozen' },
      { name: 'carrots', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'soy sauce', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'teriyaki sauce', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'eggs', unit: 'unit', amount: 2, genre: 'dairy' },
      { name: 'green onions', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'garlic', unit: 'clove', amount: 1, genre: 'produce' },
      { name: 'olive oil', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'msg', unit: 'tsp', amount: 1, genre: 'international' }
    ],
    timeMinutes: 30,
    multitaskable: false,
    cuisine: 'Asian',
    meatType: 'seafood',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'medium',
    dishType: 'main',
    recommendedSideMealIds: [ 'bao-buns' ],
    recommendedSideExtraIngredients: [
      { name: 'gyoza', unit: 'unit', amount: 1, genre: 'deli' }
    ]
  },
  {
    id: 'tom-kha-gai',
    name: 'Tom Kha Gai',
    description: 'Thai soup with shrimp, mushrooms, and coconut milk',
    ingredients: [
      { name: 'shrimp', unit: 'lb', amount: 1, genre: 'butchery' },
      { name: 'mushrooms', unit: 'cup', amount: 1, genre: 'produce' },
      { name: 'coconut milk', unit: 'oz', amount: 7, genre: 'international' },
      { name: 'ginger root', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'lemongrass', unit: 'unit', amount: 1, genre: 'international' },
      { name: 'lime leaves', unit: 'unit', amount: 1, genre: 'international' },
      { name: 'green onions', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'limes', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'fish sauce', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' },
      { name: 'chicken stock', unit: 'cup', amount: 1, genre: 'pantry' },
      { name: 'thai chilies', unit: 'unit', amount: 1, genre: 'pantry' },
      { name: 'chili flakes', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'garlic', unit: 'clove', amount: 3, genre: 'produce' }
    ],
    timeMinutes: 30,
    multitaskable: false,
    cuisine: 'Thai',
    meatType: 'seafood',
    priceLevel: '$$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'main',
    recommendedSideMealIds: ['bao-buns'],
    recommendedSideExtraIngredients: [
      { name: 'gyoza', unit: 'unit', amount: 1, genre: 'deli' }
    ]
  },
  {
    id: 'seasonal-berry-salad',
    name: 'Seasonal Berry Salad',
    description: 'Salad with fresh seasonal berries with cheese, nuts, and a tangy dressing',
    ingredients: [
      { name: 'berries', unit: 'cup', amount: 0.5, genre: 'produce' },
      { name: 'grated parmesan cheese', unit: 'cup', amount: 0.25, genre: 'deli' },
      { name: 'nuts', unit: 'cup', amount: 0.25, genre: 'produce' },
      { name: 'onion (red)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'cucumber', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'lettuce', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'spinach', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'olive oil', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'balsamic vinegar', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'jam', unit: 'cup', amount: 0.25, genre: 'pantry' }
    ],
    timeMinutes: 15,
    multitaskable: false,
    cuisine: 'American',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side'
  },
  {
    id: 'greek-salad',
    name: 'Greek Salad',
    description: 'Fresh salad with feta, olives, and cucumber',
    ingredients: [
      { name: 'cucumber', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'tomato', unit: 'unit', amount: 2, genre: 'produce' },
      { name: 'onion (red)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'radish', unit: 'cup', amount: 0.5, genre: 'produce' },
      { name: 'feta cheese', unit: 'cup', amount: 0.5, genre: 'dairy' },
      { name: 'olives', unit: 'cup', amount: 0.5, genre: 'international' },
      { name: 'olive oil', unit: 'tbsp', amount: 2, genre: 'pantry' }
    ],
    timeMinutes: 15,
    multitaskable: false,
    cuisine: 'Mediterranean',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side'
  },
  {
    id: 'fatoush-salad',
    name: 'Fatoush Salad',
    description: 'Fresh Lebanese salad with tomatoes, cucumbers, mint, and a tangy dressing',
    ingredients: [
      { name: 'tomato', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'cucumber', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'feta cheese', unit: 'cup', amount: 0.25, genre: 'dairy' },
      { name: 'onion (red)', unit: 'unit', amount: 0.5, genre: 'produce' },
      { name: 'sadaf fatoush seasoning', unit: 'tsp', amount: 1, genre: 'international' },
      { name: 'olive oil', unit: 'tbsp', amount: 2, genre: 'pantry' },
      { name: 'lemon juice', unit: 'tbsp', amount: 1, genre: 'produce' },
      { name: 'balsamic vinegar', unit: 'tbsp', amount: 1, genre: 'pantry' },
      { name: 'pomegranate molasses', unit: 'tbsp', amount: 1, genre: 'international' },
      { name: 'lettuce', unit: 'unit', amount: 1, genre: 'produce' },
      { name: 'mint', unit: 'cup', amount: 0.5, genre: 'produce' },
      { name: 'pita chips', unit: 'unit', amount: 0.25, genre: 'snacks' }
    ],
    timeMinutes: 15,
    multitaskable: false,
    cuisine: 'Mediterranean',
    meatType: 'none',
    priceLevel: '$',
    difficulty: 'easy',
    timeIntensity: 'quick',
    dishType: 'side'
  }
];



